In [1]:
import numpy as np
import pandas as pd
import math

In [2]:
run1OC = pd.read_csv("NewJersey_34021_Module6NN1stRun.csv")
run2OC = pd.read_csv("NewJersey34021Module1NN2ndRun.csv")

/anaconda2/lib/python2.7/site-packages/IPython/core/interactiveshell.py:2718: DtypeWarning: Columns (52,53,54,55,61,62,63,64) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


In [3]:
run1OC

Residence State  County Code  Tract Code  Block Code    HH ID  \
0                    34           21         100        1019  1572173   
1                    34           21         300        1015  1574011   
2                    34           21         300        1018  1574050   
3                    34           21         300        2020  1574647   
4                    34           21         300        4007  1575055   
5                    34           21         400        1009  1575588   
6                    34           21         400        1011  1575670   
7                    34           21         400        1013  1575707   
8                    34           21         400        2005  1575879   
9                    34           21         400        2006  1575918   
10                   34           21         400        2008  1575984   
11                   34           21         400        3013  1576317   
12                   34           21         500        2007  1577410   
13                   34           21         500        3007  1578083   
14                   34           21         500        3007  1578106   
15                   34           21         500        3007  1578134   
16                   34           21         600        2003  1578494   
17                   34           21         600        2012  1578633   
18                   34           21         600        2022  1578851   
19                   34           21         600        3010  1579335   
20                   34           21         800        1022  1580865   
21                   34           21         800        2012  1581203   
22                   34           21         900        2008  1582122   
23                   34           21        1000        3017  1583962   
24                   34           21        1102        1001  1585101   
25                   34           21        1102        1001  1585101   
26                   34           21        1102        2002  1585519   
27                   34           21        1102        3010  1585868   
28                   34           21        1200        2009  1587036   
29                   34           21        1300        1029  1588450   
...                 ...          ...         ...         ...      ...   
366483               34           21        4502        2020  1704866   
366484               34           21        4502        2020  1704871   
366485               34           21        4502        2020  1704873   
366486               34           21        4502        2020  1704876   
366487               34           21        4502        2020  1704877   
366488               34           21        4502        2020  1704878   
366489               34           21        4502        2020  1704880   
366490               34           21        4502        2020  1704881   
366491               34           21        4502        2020  1704881   
366492               34           21        4502        2020  1704882   
366493               34           21        4502        2020  1704882   
366494               34           21        4502        2021  1704884   
366495               34           21        4502        2021  1704887   
366496               34           21        4502        2021  1704887   
366497               34           21        4502        2021  1704889   
366498               34           21        4502        2021  1704890   
366499               34           21        4502        2021  1704890   
366500               34           21        4502        2021  1704891   
366501               34           21        4502        2021  1704892   
366502               34           21        4502        2021  1704894   
366503               34           21        4502        2021  1704896   
366504               34           21        4502        2022  1704897   
366505               34           21        4502        2022  1704

In [4]:
run2OC.head()

Unnamed: 0  Residence State  County Code  Tract Code  Block Code    HH ID  \
0     4231091               34           21         100        1002  1571615   
1     4231092               34           21         100        1002  1571616   
2     4231093               34           21         100        1002  1571617   
3     4231094               34           21         100        1002  1571618   
4     4231095               34           21         100        1002  1571619   

   HH TYPE   Latitude  Longitude  Person ID Number  Age  Sex  Traveler Type  \
0        1  40.201675 -74.754292       34004231092   88    1              0   
1        1  40.201675 -74.754292       34004231093   94    0              0   
2        1  40.201675 -74.754292       34004231094   87    0              0   
3        1  40.201675 -74.754292       34004231095   91    0              0   
4        1  40.201675 -74.754292       34004231096   85    0              0   

   Income Bracket  Income Amount  
0             0.0            0.0  
1             0.0            0.0  
2             0.0            0.0  
3             0.0            0.0  
4             0.0            0.0

In [5]:
households2 =  len(run2OC['HH ID'].unique())
print('Number of unique households: ' + str(households2))

numPeople2 = len(run2OC['Person ID Number'].unique())
print('Number of unique people: ' + str(numPeople2))

Number of unique households: 133291
Number of unique people: 366513


In [50]:
HHID = run1OC[run1OC['HH ID']==1659103]
print(HHID)

        Residence State  County Code  Tract Code  Block Code    HH ID  \
64988                34           21        3706        1002  1659103   
64989                34           21        3706        1002  1659103   
328319               34           21        3706        1002  1659103   

        Person ID Number  Activity Pattern Node 1 Type Node 1 Predecessor  \
64988        34004470302                 1           H                  N   
64989        34004470303                 1           H                  N   
328319       34004470301                 6           H                  N   

       Node 1 Successor          ...          Node 6 Departure Time  \
64988                 S          ...                          dTime   
64989                 S          ...                          dTime   
328319                O          ...                          dTime   

        Node 7 Type  Node 7 Predecessor  Node 7 Successor  Node 7 Name  \
64988           NaN                 NaN

In [51]:
HHID.shape

(3, 70)

In [52]:
#Pixelization Data
n = 138.348
def Xpixel(latitude,longitude):
    if np.isnan(latitude) or np.isnan(longitude):
        return 0
    else:
        xPixel = math.floor(n*(longitude + 97.5)*math.cos(math.radians(latitude))) 
    return xPixel
  
def Ypixel(latitude,longitude):
    if np.isnan(latitude) or np.isnan(longitude):
        return 0
    else:
        yPixel = math.floor(n*(latitude - 37.0))
        return yPixel

In [53]:
def baselat(ypixel):
    lat = ypixel/n + 37
    return lat

In [54]:
def endlat(ypixel):
    lat = (ypixel+1)/n + 37
    return lat

In [55]:
def baselong(xpixel, ypixel):
    lat = endlat(ypixel)
    return (xpixel/math.cos(math.radians(lat))/n) -97.5
def endlong(xpixel, ypixel):
    lat = baselat(ypixel)
    return ((xpixel+1)/math.cos(math.radians(lat))/n) -97.5    

In [56]:
baselat(453)

40.27435163500737

In [57]:
endlat(453)

40.28157978431202

In [58]:
baselong(2391,453)


-74.845597710358

In [59]:
endlong(2391,453)

-74.83854557138987

In [60]:
hinpixel = run1OC[run1OC['Node 1 Lat']>=baselat(453)]
hinpixel = hinpixel[hinpixel['Node 1 Lat']<endlat(453)]
hinpixel = hinpixel[hinpixel['Node 1 Lon']>=baselong(2391, 453)]
hinpixel = hinpixel[hinpixel['Node 1 Lon']<endlong(2391, 453)]
 

In [61]:
hinpixel

Residence State  County Code  Tract Code  Block Code    HH ID  \
5748                 34           21        3706        1002  1659129   
5749                 34           21        3706        1002  1659129   
5750                 34           21        3706        1002  1659129   
5751                 34           21        3706        1002  1659129   
5816                 34           21        3706        2014  1660399   
5817                 34           21        3706        2014  1660399   
9085                 34           21        3706        1002  1659129   
64988                34           21        3706        1002  1659103   
64989                34           21        3706        1002  1659103   
64990                34           21        3706        1002  1659104   
64991                34           21        3706        1002  1659104   
64992                34           21        3706        1002  1659105   
64993                34           21        3706        1002  1659105   
64994                34           21        3706        1002  1659105   
64995                34           21        3706        1002  1659106   
64996                34           21        3706        1002  1659106   
64997                34           21        3706        1002  1659106   
64998                34           21        3706        1002  1659107   
64999                34           21        3706        1002  1659107   
65000                34           21        3706        1002  1659107   
65001                34           21        3706        1002  1659108   
65002                34           21        3706        1002  1659108   
65003                34           21        3706        1002  1659108   
65004                34           21        3706        1002  1659109   
65005                34           21        3706        1002  1659109   
65006                34           21        3706        1002  1659109   
65007                34           21        3706        1002  1659110   
65008                34           21        3706        1002  1659110   
65009                34           21        3706        1002  1659110   
65010                34           21        3706        1002  1659111   
...                 ...          ...         ...         ...      ...   
329314               34           21        3706        2014  1660374   
329315               34           21        3706        2014  1660374   
329316               34           21        3706        2014  1660375   
329317               34           21        3706        2014  1660375   
329318               34           21        3706        2014  1660376   
329319               34           21        3706        2014  1660376   
329320               34           21        3706        2014  1660377   
329321               34           21        3706        2014  1660377   
329322               34           21        3706        2014  1660378   
329323               34           21        3706        2014  1660378   
329324               34           21        3706        2014  1660379   
329325               34           21        3706        2014  1660380   
329326               34           21        3706        2014  1660380   
329327               34           21        3706        2014  1660381   
329328               34           21        3706        2014  1660381   
329329               34           21        3706        2014  1660382   
329330               34           21        3706        2014  1660383   
329331               34           21        3706        2014  1660384   
329332               34           21        3706        2014  1660385   
329333               34           21        3706        2014  1660386   
329334               34           21        3706        2014  1660386   
329335               34           21        3706        2014  1660390   
329336               34           21        3706        2014  1660

In [62]:
HHID = np.asarray(HHID)
hinpixel = np.asarray(hinpixel)

In [63]:
HHID
hinpixel

array([[34, 21, 3706, ..., nan, 'oTime', 'dTime'],
       [34, 21, 3706, ..., nan, 'oTime', 'dTime'],
       [34, 21, 3706, ..., nan, 'oTime', 'dTime'],
       ...,
       [34, 21, 3706, ..., nan, 'oTime', 'dTime'],
       [34, 21, 3706, ..., nan, 'oTime', 'dTime'],
       [34, 21, 3706, ..., nan, 'oTime', 'dTime']], dtype=object)

In [64]:
run1OC_array = np.asarray(run1OC)

In [65]:
run1OC_array

array([[34, 21, 100, ..., nan, 'oTime', 'dTime'],
       [34, 21, 300, ..., nan, 'oTime', 'dTime'],
       [34, 21, 300, ..., nan, 'oTime', 'dTime'],
       ...,
       [34, 21, 4502, ..., nan, 'oTime', 'dTime'],
       [34, 21, 4502, ..., nan, 'oTime', 'dTime'],
       [34, 21, 4502, ..., nan, 'oTime', 'dTime']], dtype=object)

In [66]:
HHID

array([[34, 21, 3706, 1002, 1659103, 34004470302, 1, 'H', 'N', 'S',
        'Home', 34021, 40.276301600000004, -74.8419502, 0.0,
        '28691.321377576758', 'S', 'H', 'H', 'EWING HIGH', 34021.0,
        40.254961, -74.78967, '29066.850908248216', '57744.54613954459',
        'H', 'S', 'O', 'Home', 34021.0, 40.276301600000004, -74.8419502,
        '58120.07567021604', '59249.70330200619', 'O', 'H', 'H',
        'HONEY BROOK ORGANIC FARM', 34021.0, 40.3551, -74.76266600000001,
        '60045.64808330615', '66474.14373300674', 'H', 'O', 'N', 'Home',
        34021.0, 40.276301600000004, -74.8419502, '67271.30098973667',
        nan, nan, nan, nan, nan, nan, nan, nan, 'oTime', 'dTime', nan,
        nan, nan, nan, nan, nan, nan, 'oTime', 'dTime'],
       [34, 21, 3706, 1002, 1659103, 34004470303, 1, 'H', 'N', 'S',
        'Home', 34021, 40.276301600000004, -74.8419502, 0.0,
        '27070.0283024705', 'S', 'H', 'O', 'EWING HIGH', 34021.0,
        40.254961, -74.78967, '27445.557833141957',

In [67]:
def pixelization(n,a):
    xpixels =  np.zeros((n,7))
    ypixels =  np.zeros((n,7))
    oarrivals = np.zeros((n,7))
    odepartures = np.zeros((n,7))
    latlong = np.zeros((n*7,3))

    name = [[] for _ in range(n)]
    for i in range(n):
        for j in range(7):
            xpixels[i][j]= Xpixel(a[i][12+9*j],a[i][13+9*j])
            ypixels[i][j]= Ypixel(a[i][12+9*j],a[i][13+9*j])
            latlong[i*7 + j][0] = a[i][12+9*j]
            latlong[i*7 + j][1] = a[i][13+9*j]
            latlong[i*7 + j ][2] = a[i][13+9*j]*a[i][12+9*j]
            if a[i][14+9*j] != 'oTime':
                oarrivals[i][j]= (a[i][14+9*j])
            else:
                oarrivals[i][j]= 0
            b = a[i][15+9*j]
            print(b)
            if a[i][15+9*j] == 'dTime' or pd.isnull(b):
                odepartures[i][j]= 0
            else:
                if float(a[i][15+9*j]) >= 90000:
                    odepartures[i][j]= 0
                else:
                    odepartures[i][j]= (a[i][15+9*j])
                
            name[i] = np.append(name[i], a[i][10+9*j])
    return xpixels, ypixels, name, oarrivals, odepartures, latlong


In [68]:
# change first number to amt of ppl in classroom
pixelization(3, HHID)
pixelization(345, hinpixel)

28691.321377576758
57744.54613954459
59249.70330200619
66474.14373300674
nan
dTime
dTime
27070.0283024705
57494.117992027495
64711.88168923174
nan
dTime
dTime
dTime
36566.643526979475
42194.72649266568
47297.12817748388
nan
dTime
dTime
dTime
25383.36630310581
61346.034411437206
64480.638487011725
68993.56857385978
73766.43650547278
nan
dTime
30622.7784465961
59010.76303079494
61697.197452169115
67201.2270669111
72569.66065553563
nan
dTime
39070.18505608865
72076.80120657483
79654.26353149021
nan
dTime
dTime
dTime
28190.324731470155
65361.50883243437
71763.71676750791
83578.49211186286
nan
dTime
dTime
27924.596666099067
58313.23124755686
73894.64672981581
nan
dTime
dTime
dTime
38299.07759032445
71883.47379387438
74654.68448356989
82535.69141140152
nan
dTime
dTime
25934.538956240605
61350.04691600932
66423.79814126327
75973.1995228614
80792.70791900465
nan
dTime
28691.321377576758
57744.54613954459
59249.70330200619
66474.14373300674
nan
dTime
dTime
27070.0283024705
57494.117992027495
64

74411.25144138698
nan
dTime
dTime
31295.219515980225
60928.86429398683
66882.25092946924
72854.820840802
nan
dTime
dTime
38268.26050262459
72376.22228325155
77982.00796215361
83585.83592055863
89443.35998966737
93431.1043208475
99315.89913849242
55803.86634905208
93575.83488324509
99817.20332379382
113412.16582426014
nan
dTime
dTime
38910.38838823289
72329.54701133721
76647.36451138857
81457.28013785578
88959.84380097232
nan
dTime
38630.51399274352
72133.76608302062
75814.4310200569
81557.38346037663
nan
dTime
dTime
31287.276399994495
61614.880937455615
nan
dTime
dTime
dTime
dTime
31491.17470692057
61027.236283061175
67257.29864934304
nan
dTime
dTime
dTime
29836.808894109698
59417.03366805927
63780.00759354219
nan
dTime
dTime
dTime
31014.858566779898
66450.74237986903
70776.36476470107
78293.12414820987
82595.8706651006
nan
dTime
37569.82589218758
72034.01310247014
75349.85389709864
81259.78904166132
87693.89126065197
nan
dTime
37949.98855103947
72085.23996855567
78575.79163001271
8168

47155.06086471555
52658.893673531886
nan
dTime
dTime
dTime
dTime
dTime
dTime
dTime
dTime
dTime
dTime
38161.35539057853
44102.80223603771
dTime
dTime
dTime
dTime
dTime
36164.89677562946
41855.54432598379
dTime
dTime
dTime
dTime
dTime
37255.741642724
43808.19496730823
46748.60338659205
52962.5873227443
nan
dTime
dTime
38237.6277849998
44238.96474139999
dTime
dTime
dTime
dTime
dTime
37645.04547895087
44019.72633353015
50616.828647282935
nan
dTime
dTime
dTime
41999.383980285136
47204.007811815456
54144.91354986441
nan
dTime
dTime
dTime
36566.643526979475
42194.72649266568
47297.12817748388
nan
dTime
dTime
dTime
dTime
dTime
dTime
dTime
dTime
dTime
dTime
41977.653758352404
49027.43394579503
55524.12970354813
nan
dTime
dTime
dTime
38842.0235570024
46155.537984994575
dTime
dTime
dTime
dTime
dTime
43172.836572288856
49859.754509760445
54530.329600148405
nan
dTime
dTime
dTime
dTime
dTime
dTime
dTime
dTime
dTime
dTime
dTime
dTime
dTime
dTime
dTime
dTime
dTime
dTime
dTime
dTime
dTime
dTime
dTime
d

(array([[2391., 2415., 2391., ..., 2390., 2391.,    0.],
        [2391., 2395., 2391., ..., 2391., 2391.,    0.],
        [2391., 2403., 2416., ...,    0.,    0.,    0.],
        ...,
        [2391., 2388., 2391., ...,    0.,    0.,    0.],
        [2391.,    0.,    0., ...,    0.,    0.,    0.],
        [2391., 2388., 2391., ...,    0.,    0.,    0.]]),
 array([[453., 456., 453., ..., 455., 453.,   0.],
        [453., 451., 453., ..., 461., 453.,   0.],
        [453., 444., 438., ...,   0.,   0.,   0.],
        ...,
        [453., 461., 453., ...,   0.,   0.,   0.],
        [453.,   0.,   0., ...,   0.,   0.,   0.],
        [453., 461., 453., ...,   0.,   0.,   0.]]),
 [array(['Home', 'ACCURATE SOFTWARES INTL INC', 'Home', 'JANSSEN FARM',
         'JANSSEN FARM', 'Home', 'nan'], dtype='|S32'),
  array(['Home', 'AUDIO SPEECH & HEARING AID', 'Home', 'SOUTHWIND FARM',
         'SOUTHWIND FARM', 'Home', 'nan'], dtype='|S32'),
  array(['Home', "TRENTINI'S RESTAURANT", 'EVERGREEN ORCHARD FA

In [69]:
def cartDist(n, xpixels, ypixels):
    distances = np.zeros((n,6))
    for i in range(n):
        for j in range(6):
            if xpixels[i][j+1] == 0:
                break
            else:
                distances[i][j]=math.sqrt(((xpixels[i][j+1]-xpixels[i][j])**2) + ((ypixels[i][j+1]-ypixels[i][j])**2))
            
    return distances

In [71]:

xpixels, ypixels, names, oarrivals, odepartures, latlong = pixelization(345,hinpixel)

25383.36630310581
61346.034411437206
64480.638487011725
68993.56857385978
73766.43650547278
nan
dTime
30622.7784465961
59010.76303079494
61697.197452169115
67201.2270669111
72569.66065553563
nan
dTime
39070.18505608865
72076.80120657483
79654.26353149021
nan
dTime
dTime
dTime
28190.324731470155
65361.50883243437
71763.71676750791
83578.49211186286
nan
dTime
dTime
27924.596666099067
58313.23124755686
73894.64672981581
nan
dTime
dTime
dTime
38299.07759032445
71883.47379387438
74654.68448356989
82535.69141140152
nan
dTime
dTime
25934.538956240605
61350.04691600932
66423.79814126327
75973.1995228614
80792.70791900465
nan
dTime
28691.321377576758
57744.54613954459
59249.70330200619
66474.14373300674
nan
dTime
dTime
27070.0283024705
57494.117992027495
64711.88168923174
nan
dTime
dTime
dTime
28379.345915015114
56983.462622474515
59518.7029079349
66896.69320682315
nan
dTime
dTime
28424.404880844282
58690.481448872066
65236.63588143318
71265.64365388814
77576.8548686475
nan
dTime
27282.12833050

31586.174659584492
61163.19637574501
67563.73685889906
71772.7055388161
78649.05347059197
81864.11476605528
87842.88729982737
31926.45835105127
61162.84743871941
68023.70794990074
70754.68957683182
76995.90152420173
82989.19094561198
90796.34023366548
29734.682405788804
61028.39904965247
68826.84992328934
74348.01561179875
81501.78154588981
86026.83786668676
91701.77428254846
29004.640283174384
61236.31422956164
68173.36341523391
71051.61987723685
77950.0373790744
nan
dTime
31604.3736831947
61381.036650755195
63897.54492250705
70229.24929412837
75873.34237674464
nan
dTime
31704.5346380561
66694.46852539509
72534.05347320971
77624.86078958912
82980.03297669985
nan
dTime
31621.014709089497
61193.611042279095
64242.03815808794
70706.68980753873
nan
dTime
dTime
29367.64043095495
57547.05652668439
63437.87728069659
70346.49776478107
77327.5351384048
79623.71426966327
85278.48771964392
38830.95121621986
71897.88523644171
78915.41886264103
84384.94408489716
90145.26707705371
nan
dTime
29531.7

dTime
dTime
dTime
dTime
dTime
dTime
dTime
dTime
dTime
dTime
dTime
dTime
dTime
dTime
dTime
dTime
dTime
dTime
dTime
dTime
dTime
dTime
dTime
41117.73187183819
47879.96719706603
dTime
dTime
dTime
dTime
dTime
dTime
dTime
dTime
dTime
dTime
dTime
dTime
dTime
dTime
dTime
dTime
dTime
dTime
dTime
37522.106161939635
43270.430830884805
47443.19476099009
nan
dTime
dTime
dTime
36187.245468166264
41727.18807830467
47247.2194600157
nan
dTime
dTime
dTime
36265.19468911814
40866.77965690712
43805.077499253806
48895.663334944824
nan
dTime
dTime
39069.44282833527
44138.91272477643
49429.99385435426
nan
dTime
dTime
dTime
40980.70269475663
47991.528025316475
53374.11810192029
nan
dTime
dTime
dTime
40420.54795092619
45971.5983504573
dTime
dTime
dTime
dTime
dTime
dTime
dTime
dTime
dTime
dTime
dTime
dTime
dTime
dTime
dTime
dTime
dTime
dTime
dTime
dTime
dTime
dTime
dTime
dTime
dTime
dTime
dTime
dTime
dTime
dTime
dTime
dTime
dTime
dTime
dTime
dTime
dTime
dTime
dTime
dTime
dTime
dTime
dTime
dTime
dTime
dTime
dTim

In [72]:
xpixels

array([[2391., 2415., 2391., ..., 2390., 2391.,    0.],
       [2391., 2395., 2391., ..., 2391., 2391.,    0.],
       [2391., 2403., 2416., ...,    0.,    0.,    0.],
       ...,
       [2391., 2388., 2391., ...,    0.,    0.,    0.],
       [2391.,    0.,    0., ...,    0.,    0.,    0.],
       [2391., 2388., 2391., ...,    0.,    0.,    0.]])

In [73]:
dist = cartDist(345,xpixels, ypixels)
odepartures
np.nan_to_num(odepartures)

array([[25383.36630311, 61346.03441144, 64480.63848701, ...,
        73766.43650547,     0.        ,     0.        ],
       [30622.7784466 , 59010.76303079, 61697.19745217, ...,
        72569.66065554,     0.        ,     0.        ],
       [39070.18505609, 72076.80120657, 79654.26353149, ...,
            0.        ,     0.        ,     0.        ],
       ...,
       [36120.14832023, 42861.82008689,     0.        , ...,
            0.        ,     0.        ,     0.        ],
       [    0.        ,     0.        ,     0.        , ...,
            0.        ,     0.        ,     0.        ],
       [36725.55872804, 42848.86743902,     0.        , ...,
            0.        ,     0.        ,     0.        ]])

In [74]:
np.sum(dist, axis=1)

array([ 52.84568244,  24.94427191,  58.47258054,  53.85677655,
        49.61924677,  93.40590646, 194.74083358,  38.47633604,
        71.67590286,  34.95706709,  87.40460384,  30.50441536,
        29.41640786,  55.0266881 ,  62.60990337,  53.8824847 ,
        32.01533972,  44.65098185,  27.11775265,  31.71030397,
        50.61855834,  30.50441536,  27.11775265,  83.95655575,
        69.86377459,  76.7977946 ,  33.32396858,  54.69960134,
        20.64222328,  28.62654061,  81.58431222,  25.20711964,
        24.62024413,  24.34017465,  13.41640786,  60.14889513,
        61.30495168,  69.86377459,  47.23690263,   6.47213595,
        30.        ,  17.40914158,   2.        ,  45.01198669,
         2.        ,  55.85164807,  60.30951895,  16.4222051 ,
       118.93043477,  34.95706709,  82.29758019,  17.88854382,
       165.79806382, 103.32891558,  21.54065923,  58.83836945,
       116.41855171, 101.44326383,  67.26805594,  67.26805594,
        97.46115671,  17.88854382, 171.13430752,  26.83

In [75]:
len(np.nonzero(dist)[0])

1121

In [76]:
print(dist)

[[24.18677324 24.18677324  2.23606798  0.          2.23606798  0.        ]
 [ 4.47213595  4.47213595  8.          0.          8.          0.        ]
 [15.         14.31782106 29.15475947  0.          0.          0.        ]
 ...
 [ 8.54400375  8.54400375  0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.          0.          0.        ]
 [ 8.54400375  8.54400375  0.          0.          0.          0.        ]]


In [113]:
def tripInfo(n, distances, odepartures):
    count = 0
    tripsPP= np.zeros(n)
    tripsPH = np.zeros(25)
    for i in range(n):
        for j in range(6):
            if distances[i][j] == 0:
                count = 0
            else:
                tripsPP[i] += 1
            if np.isnan(odepartures[i][j]) or odepartures[i][j] == 0 or odepartures[i][j] == 'dTime':
                count = 0
            else:
                print(math.floor(odepartures[i][j]/3600.))
                tripsPH[int(math.floor(odepartures[i][j]/3600.))] += 1;
                
    return tripsPP, tripsPH
    
            

In [114]:
odepartures


array([[25383.36630311, 61346.03441144, 64480.63848701, ...,
        73766.43650547,     0.        ,     0.        ],
       [30622.7784466 , 59010.76303079, 61697.19745217, ...,
        72569.66065554,     0.        ,     0.        ],
       [39070.18505609, 72076.80120657, 79654.26353149, ...,
            0.        ,     0.        ,     0.        ],
       ...,
       [36120.14832023, 42861.82008689,     0.        , ...,
            0.        ,     0.        ,     0.        ],
       [    0.        ,     0.        ,     0.        , ...,
            0.        ,     0.        ,     0.        ],
       [36725.55872804, 42848.86743902,     0.        , ...,
            0.        ,     0.        ,     0.        ]])

In [115]:
tripInfo(345, dist, odepartures)

7.0
17.0
17.0
19.0
20.0
8.0
16.0
17.0
18.0
20.0
10.0
20.0
22.0
7.0
18.0
19.0
23.0
7.0
16.0
20.0
10.0
19.0
20.0
22.0
7.0
17.0
18.0
21.0
22.0
7.0
16.0
16.0
18.0
7.0
15.0
17.0
7.0
15.0
16.0
18.0
7.0
16.0
18.0
19.0
21.0
7.0
15.0
17.0
18.0
7.0
16.0
17.0
19.0
7.0
16.0
17.0
7.0
16.0
17.0
18.0
20.0
7.0
16.0
17.0
7.0
16.0
17.0
17.0
19.0
7.0
16.0
17.0
18.0
19.0
8.0
16.0
17.0
7.0
16.0
17.0
18.0
20.0
7.0
16.0
16.0
18.0
7.0
16.0
17.0
19.0
7.0
15.0
17.0
7.0
15.0
18.0
19.0
21.0
8.0
16.0
16.0
19.0
7.0
16.0
18.0
19.0
21.0
8.0
16.0
18.0
18.0
20.0
7.0
15.0
17.0
19.0
21.0
7.0
16.0
17.0
19.0
21.0
7.0
16.0
17.0
18.0
20.0
8.0
15.0
16.0
18.0
20.0
7.0
16.0
17.0
7.0
15.0
16.0
17.0
8.0
15.0
17.0
18.0
7.0
16.0
7.0
16.0
18.0
18.0
20.0
7.0
15.0
17.0
19.0
21.0
7.0
16.0
17.0
19.0
7.0
16.0
17.0
19.0
20.0
7.0
15.0
16.0
18.0
7.0
15.0
17.0
7.0
15.0
17.0
7.0
16.0
7.0
15.0
16.0
18.0
20.0
7.0
16.0
7.0
16.0
17.0
19.0
7.0
16.0
17.0
18.0
7.0
15.0
16.0
18.0
7.0
15.0
17.0
19.0
8.0
16.0
16.0
18.0
7.0
16.0
18.0
18.0
20.0
7.0
15.0


(array([4., 4., 3., 4., 3., 4., 5., 4., 3., 4., 5., 4., 4., 3., 5., 3., 5.,
        5., 3., 5., 4., 4., 3., 5., 4., 5., 5., 5., 5., 5., 4., 3., 4., 4.,
        2., 5., 5., 4., 5., 4., 3., 3., 2., 5., 2., 4., 4., 4., 4., 4., 5.,
        4., 4., 4., 2., 3., 4., 3., 4., 4., 5., 4., 6., 3., 3., 4., 4., 3.,
        6., 4., 4., 4., 3., 3., 3., 4., 5., 3., 5., 4., 6., 4., 4., 4., 3.,
        4., 4., 5., 6., 4., 3., 3., 5., 4., 4., 4., 4., 3., 5., 4., 4., 4.,
        3., 4., 6., 3., 4., 4., 6., 3., 4., 3., 5., 4., 4., 5., 4., 4., 4.,
        5., 4., 4., 5., 4., 4., 4., 4., 4., 6., 4., 5., 4., 2., 3., 3., 4.,
        5., 5., 5., 5., 3., 5., 4., 5., 5., 4., 4., 6., 6., 6., 5., 4., 4.,
        4., 6., 5., 4., 4., 3., 5., 6., 4., 4., 6., 5., 2., 6., 3., 4., 4.,
        5., 5., 5., 3., 6., 3., 4., 3., 2., 5., 2., 4., 2., 6., 4., 0., 4.,
        6., 5., 3., 4., 5., 4., 5., 5., 4., 4., 3., 6., 4., 3., 2., 2., 5.,
        4., 4., 3., 6., 4., 5., 4., 4., 4., 3., 2., 6., 4., 2., 5., 4., 5.,
        5., 

In [116]:
pixels = np.zeros((10000,3))
latlong

array([[   40.2763016 ,   -74.8419502 , -3014.35695859],
       [   40.299864  ,   -74.605469  , -3006.59025436],
       [   40.2763016 ,   -74.8419502 , -3014.35695859],
       ...,
       [           nan,            nan,            nan],
       [           nan,            nan,            nan],
       [           nan,            nan,            nan]])

In [117]:
u_pixels = np.unique(latlong, axis = 0)

In [118]:
i = 0
while True:
    pixels[i][0] = u_pixels[i][0]
    pixels[i][1] = u_pixels[i][1]
    pixels[i][2] = np.count_nonzero(latlong == u_pixels[i][2])
    i = i + 1
    if np.isnan(u_pixels[i][0]):
        break
pixels

array([[ 39.276719, -76.561517,   1.      ],
       [ 39.357946, -76.553037,   1.      ],
       [ 39.862531, -74.815616,   2.      ],
       ...,
       [  0.      ,   0.      ,   0.      ],
       [  0.      ,   0.      ,   0.      ],
       [  0.      ,   0.      ,   0.      ]])

In [107]:
xpixels

array([[2391., 2415., 2391., ..., 2390., 2391.,    0.],
       [2391., 2395., 2391., ..., 2391., 2391.,    0.],
       [2391., 2403., 2416., ...,    0.,    0.,    0.],
       ...,
       [2391., 2388., 2391., ...,    0.,    0.,    0.],
       [2391.,    0.,    0., ...,    0.,    0.,    0.],
       [2391., 2388., 2391., ...,    0.,    0.,    0.]])

In [108]:
ypixels

array([[453., 456., 453., ..., 455., 453.,   0.],
       [453., 451., 453., ..., 461., 453.,   0.],
       [453., 444., 438., ...,   0.,   0.,   0.],
       ...,
       [453., 461., 453., ...,   0.,   0.,   0.],
       [453.,   0.,   0., ...,   0.,   0.,   0.],
       [453., 461., 453., ...,   0.,   0.,   0.]])

In [109]:
import csv

with open('Mercer1.csv', 'w') as csvFile:
    writer = csv.writer(csvFile)
    writer.writerows(pixels)

csvFile.close()


NameError: name 'tripsPP' is not defined