In [1]:
import numpy as np
import pandas as pd
import math

In [2]:
run1OC = pd.read_csv("NewYork_36071_Module6NN1stRun.csv")
run2OC = pd.read_csv("NewYork36071Module1NN2ndRun.csv")

/Users/wylyanderson/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2698: DtypeWarning: Columns (52,53,54,55,61,62,63,64) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


In [3]:
run1OC

Residence State  County Code  Tract Code  Block Code    HH ID  \
0                    36           71       13900        2021  4668505   
1                    36           71         100        1017  4576906   
2                    36           71         100        1018  4576932   
3                    36           71         100        1019  4576950   
4                    36           71         100        1019  4576952   
5                    36           71         100        3001  4577575   
6                    36           71         200        1003  4577856   
7                    36           71         200        1003  4577861   
8                    36           71         200        1003  4577868   
9                    36           71         200        2001  4578373   
10                   36           71         200        2001  4578382   
11                   36           71         200        2003  4578437   
12                   36           71         200        2006  4578506   
13                   36           71         300        1000  4578608   
14                   36           71         300        1004  4578694   
15                   36           71         300        1013  4578897   
16                   36           71         300        2008  4579202   
17                   36           71         300        2009  4579213   
18                   36           71         300        2010  4579239   
19                   36           71         300        2010  4579242   
20                   36           71         300        2011  4579282   
21                   36           71         300        2014  4579406   
22                   36           71         300        2015  4579463   
23                   36           71         300        2017  4579488   
24                   36           71         300        3004  4579624   
25                   36           71         300        3005  4579678   
26                   36           71         300        4001  4579900   
27                   36           71         300        4006  4580025   
28                   36           71         300        4007  4580067   
29                   36           71         300        4008  4580099   
...                 ...          ...         ...         ...      ...   
372783               36           71       15200        6092  4702761   
372784               36           71       15200        6092  4702762   
372785               36           71       15200        6092  4702762   
372786               36           71       15200        6092  4702762   
372787               36           71       15200        6092  4702762   
372788               36           71       15200        6092  4702762   
372789               36           71       15200        6092  4702763   
372790               36           71       15200        6092  4702763   
372791               36           71       15200        6092  4702763   
372792               36           71       15200        6092  4702764   
372793               36           71       15200        6092  4702764   
372794               36           71       15200        6092  4702764   
372795               36           71       15200        6092  4702764   
372796               36           71       15200        6093  4702765   
372797               36           71       15200        6093  4702766   
372798               36           71       15200        6094  4702767   
372799               36           71       15200        6094  4702769   
372800               36           71       15200        6094  4702774   
372801               36           71       15200        6094  4702775   
372802               36           71       15200        6094  4702776   
372803               36           71       15200        6095  4702777   
372804               36           71       15200        6095  4702781   
372805               36           71       15200        6095  4702

In [4]:
run2OC.head()

Unnamed: 0  Residence State  County Code  Tract Code  Block Code    HH ID  \
0    11690759               36           71         100        1000  4576658   
1    11690760               36           71         100        1000  4576658   
2    11690761               36           71         100        1000  4576659   
3    11690762               36           71         100        1000  4576659   
4    11690763               36           71         100        1001  4576660   

   HH TYPE   Latitude  Longitude  Person ID Number  Age  Sex  Traveler Type  \
0        1  41.517333 -74.012504       36011690760   66    1              6   
1        1  41.517333 -74.012504       36011690761   17    1              1   
2        0  41.517333 -74.012504       36011690762   53    1              5   
3        0  41.517333 -74.012504       36011690763   59    0              5   
4        1  41.517446 -74.014654       36011690764   76    0              6   

   Income Bracket  Income Amount  
0             6.0   69012.044610  
1             0.0       0.000000  
2             1.0    2409.692110  
3             1.0    6393.542108  
4             5.0   45906.476360

In [5]:
households2 =  len(run2OC['HH ID'].unique())
print('Number of unique households: ' + str(households2))

numPeople2 = len(run2OC['Person ID Number'].unique())
print('Number of unique people: ' + str(numPeople2))

Number of unique households: 126132
Number of unique people: 372813


In [6]:
allyHHID = run1OC[run1OC['HH ID']==4643185]
print(allyHHID)

        Residence State  County Code  Tract Code  Block Code    HH ID  \
56600                36           71       12200        1017  4643185   
56601                36           71       12200        1017  4643185   
56602                36           71       12200        1017  4643185   
56603                36           71       12200        1017  4643185   
314699               36           71       12200        1017  4643185   

        Person ID Number  Activity Pattern Node 1 Type Node 1 Predecessor  \
56600        36011882014                 1           H                  N   
56601        36011882015                 1           H                  N   
56602        36011882016                 1           H                  N   
56603        36011882017                 1           H                  N   
314699       36011882013                 6           H                  N   

       Node 1 Successor          ...          Node 6 Departure Time  \
56600                 S    

In [7]:
allyHHID.shape

(5, 70)

In [8]:
#Pixelization Data
n = 138.348
def Xpixel(latitude,longitude):
    if np.isnan(latitude) or np.isnan(longitude):
        return 0
    else:
        xPixel = math.floor(n*(longitude + 97.5)*math.cos(math.radians(latitude))) 
    return xPixel
  
def Ypixel(latitude,longitude):
    if np.isnan(latitude) or np.isnan(longitude):
        return 0
    else:
        yPixel = math.floor(n*(latitude - 37.0))
        return yPixel

In [9]:
def baselat(ypixel):
    lat = ypixel/n + 37
    return lat

In [10]:
def endlat(ypixel):
    lat = (ypixel+1)/n + 37
    return lat

In [11]:
def baselong(xpixel, ypixel):
    lat = endlat(ypixel)
    return (xpixel/math.cos(math.radians(lat))/n) -97.5
def endlong(xpixel, ypixel):
    lat = baselat(ypixel)
    return ((xpixel+1)/math.cos(math.radians(lat))/n) -97.5    

In [12]:
baselat(610)

41.40917107583774

In [13]:
endlat(610)

41.41639922514239

In [14]:
baselong(2403,610)


-74.33859336548741

In [15]:
endlong(2403,610)

-74.33153294110518

In [16]:
hinpixel = run1OC[run1OC['Node 1 Lat']>=baselat(610)]
hinpixel = hinpixel[hinpixel['Node 1 Lat']<endlat(610)]
hinpixel = hinpixel[hinpixel['Node 1 Lon']>=baselong(2403, 610)]
hinpixel = hinpixel[hinpixel['Node 1 Lon']<endlong(2403, 610)]
 

In [17]:
hinpixel

Residence State  County Code  Tract Code  Block Code    HH ID  \
6498                 36           71       12200        1017  4643190   
54331                36           71       11900        1017  4639677   
54332                36           71       11900        1017  4639678   
54333                36           71       11900        1017  4639678   
54334                36           71       11900        1017  4639678   
54335                36           71       11900        1017  4639679   
54336                36           71       11900        1017  4639679   
54337                36           71       11900        1017  4639679   
54338                36           71       11900        1017  4639680   
54339                36           71       11900        1017  4639680   
54452                36           71       11900        1063  4639822   
54453                36           71       11900        1063  4639823   
54454                36           71       11900        1063  4639823   
54455                36           71       11900        1063  4639823   
56590                36           71       12200        1017  4643181   
56591                36           71       12200        1017  4643181   
56592                36           71       12200        1017  4643182   
56593                36           71       12200        1017  4643182   
56594                36           71       12200        1017  4643183   
56595                36           71       12200        1017  4643183   
56596                36           71       12200        1017  4643183   
56597                36           71       12200        1017  4643184   
56598                36           71       12200        1017  4643184   
56599                36           71       12200        1017  4643184   
56600                36           71       12200        1017  4643185   
56601                36           71       12200        1017  4643185   
56602                36           71       12200        1017  4643185   
56603                36           71       12200        1017  4643185   
56604                36           71       12200        1017  4643186   
56605                36           71       12200        1017  4643186   
...                 ...          ...         ...         ...      ...   
311363               36           71       11900        1063  4639819   
311364               36           71       11900        1063  4639820   
311365               36           71       11900        1063  4639821   
311366               36           71       11900        1063  4639822   
311367               36           71       11900        1063  4639822   
311368               36           71       11900        1063  4639823   
311369               36           71       11900        1063  4639823   
311370               36           71       11900        1063  4639823   
314683               36           71       12200        1017  4643170   
314684               36           71       12200        1017  4643170   
314685               36           71       12200        1017  4643171   
314686               36           71       12200        1017  4643172   
314687               36           71       12200        1017  4643173   
314688               36           71       12200        1017  4643174   
314689               36           71       12200        1017  4643174   
314690               36           71       12200        1017  4643175   
314691               36           71       12200        1017  4643176   
314692               36           71       12200        1017  4643177   
314693               36           71       12200        1017  4643178   
314694               36           71       12200        1017  4643179   
314695               36           71       12200        1017  4643179   
314696               36           71       12200        1017  4643182   
314697               36           71       12200        1017  4643

In [18]:
allyHHID = np.asarray(allyHHID)
hinpixel = np.asarray(hinpixel)

In [19]:
allyHHID
hinpixel

array([[36, 71, 12200, ..., nan, 'oTime', 'dTime'],
       [36, 71, 11900, ..., nan, 'oTime', 'dTime'],
       [36, 71, 11900, ..., nan, 'oTime', 'dTime'],
       ..., 
       [36, 71, 12200, ..., nan, 'oTime', 'dTime'],
       [36, 71, 12200, ..., nan, 'oTime', 'dTime'],
       [36, 71, 12200, ..., nan, 'oTime', 'dTime']], dtype=object)

In [20]:
run1OC_array = np.asarray(run1OC)

In [21]:
run1OC_array

array([[36, 71, 13900, ..., nan, 'oTime', 'dTime'],
       [36, 71, 100, ..., nan, 'oTime', 'dTime'],
       [36, 71, 100, ..., nan, 'oTime', 'dTime'],
       ..., 
       [36, 71, 15200, ..., nan, 'oTime', 'dTime'],
       [36, 71, 15200, ..., nan, 'oTime', 'dTime'],
       [36, 71, 15200, ..., nan, 'oTime', 'dTime']], dtype=object)

In [22]:
allyHHID

array([[36, 71, 12200, 1017, 4643185, 36011882014, 1, 'H', 'N', 'S',
        'Home', 36071, 41.4122136, -74.3321119, 0, '29131.19432', 'S', 'H',
        'O', 'SCOTCHTOWN AVENUE SCHOOL', 36071.0, 41.414171, -74.323418,
        '29187.69993', '58203.18873', 'O', 'S', 'H', nan, 36071.0,
        41.400628999999995, -74.330281, '58323.43963', '64359.37662', 'H',
        'O', 'N', 'Home', 36071.0, 41.4122136, -74.3321119, '63617.33476',
        nan, nan, nan, nan, nan, nan, nan, nan, 'oTime', 'dTime', nan, nan,
        nan, nan, nan, nan, nan, 'oTime', 'dTime', nan, nan, nan, nan, nan,
        nan, nan, 'oTime', 'dTime'],
       [36, 71, 12200, 1017, 4643185, 36011882015, 1, 'H', 'N', 'S',
        'Home', 36071, 41.4122136, -74.3321119, 0, '28638.77485', 'S', 'H',
        'O', 'SCOTCHTOWN AVENUE SCHOOL', 36071.0, 41.414171, -74.323418,
        '28695.28046', '59242.29968', 'O', 'S', 'H',
        'SLEEPY HILLS ORCHARD', 36071.0, 41.365066999999996,
        -74.50639100000001, '60452.42241', '

In [35]:
def pixelization(n,a):
    xpixels =  np.zeros((n,7))
    ypixels =  np.zeros((n,7))
    oarrivals = np.zeros((n,7))
    odepartures = np.zeros((n,7))
    latlong = np.zeros((n*7,3))

    name = [[] for _ in range(n)]
    for i in range(n):
        for j in range(7):
            xpixels[i][j]= Xpixel(a[i][12+9*j],a[i][13+9*j])
            ypixels[i][j]= Ypixel(a[i][12+9*j],a[i][13+9*j])
            latlong[i*7 + j][0] = a[i][12+9*j]
            latlong[i*7 + j][1] = a[i][13+9*j]
            latlong[i*7 + j ][2] = a[i][13+9*j]*a[i][12+9*j]
            if a[i][14+9*j] != 'oTime':
                oarrivals[i][j]= (a[i][14+9*j])
            else:
                oarrivals[i][j]= 0
            b = a[i][15+9*j]
            print(b)
            if a[i][15+9*j] == 'dTime' or pd.isnull(b):
                odepartures[i][j]= 0
            else:
                if float(a[i][15+9*j]) >= 90000:
                    odepartures[i][j]= 0
                else:
                    odepartures[i][j]= (a[i][15+9*j])
                
            name[i] = np.append(name[i], a[i][10+9*j])
    return xpixels, ypixels, name, oarrivals, odepartures, latlong


In [36]:
pixelization(5, allyHHID)
pixelization(124, hinpixel)

29131.19432
58203.18873
64359.37662
nan
dTime
dTime
dTime
28638.77485
59242.29968
66370.46234
nan
dTime
dTime
dTime
27956.52105
58618.05205
nan
dTime
dTime
dTime
dTime
28404.73326
55912.01204
62946.63594
68657.12911
74447.90663
nan
dTime
38376.02157
44181.59813
49826.24473
nan
dTime
dTime
dTime
39097.31413
71910.02156
77388.55087
85301.80221
91576.1033
nan
dTime
29239.4693
57297.69063
61480.66534
68346.75738
nan
dTime
dTime
28883.25981
57642.36077
nan
dTime
dTime
dTime
dTime
28515.55434
57043.12402
63987.60518
nan
dTime
dTime
dTime
28401.76928
56888.61875
62656.41347
nan
dTime
dTime
dTime
27368.50559
57629.2452
63343.67296
nan
dTime
dTime
dTime
27659.39777
57393.90247
64318.99363
67982.53847
72619.70497
77316.53861
84123.60382
30044.70594
57230.72229
61064.4705
67788.15072
nan
dTime
dTime
29519.73661
58619.05505
63429.53289
nan
dTime
dTime
dTime
25468.85845
59180.69034
67369.40147
nan
dTime
dTime
dTime
28364.90155
56800.00794
61423.5845
66618.09958
72829.74847
nan
dTime
29312.16449
578

(array([[ 2403.,  2393.,  2403.,  2426.,  2426.,  2403.,     0.],
        [ 2403.,  2404.,  2403.,  2431.,  2403.,     0.,     0.],
        [ 2403.,  2404.,  2403.,     0.,     0.,     0.,     0.],
        [ 2403.,  2404.,  2413.,  2403.,     0.,     0.,     0.],
        [ 2403.,  2404.,  2422.,  2403.,     0.,     0.,     0.],
        [ 2403.,  2404.,  2404.,  2403.,     0.,     0.,     0.],
        [ 2403.,  2404.,  2413.,  2403.,  2405.,  2403.,  2422.],
        [ 2403.,  2404.,  2403.,  2404.,  2403.,     0.,     0.],
        [ 2403.,  2404.,  2396.,  2403.,     0.,     0.,     0.],
        [ 2403.,  2439.,  2403.,  2403.,     0.,     0.,     0.],
        [ 2403.,  2404.,  2403.,  2403.,  2409.,  2403.,     0.],
        [ 2403.,  2404.,  2398.,  2403.,     0.,     0.,     0.],
        [ 2403.,  2404.,  2403.,     0.,     0.,     0.,     0.],
        [ 2403.,  2404.,  2396.,  2403.,     0.,     0.,     0.],
        [ 2403.,  2404.,  2407.,  2403.,  2400.,  2403.,     0.],
        [ 

In [37]:
def cartDist(n, xpixels, ypixels):
    distances = np.zeros((n,6))
    for i in range(n):
        for j in range(6):
            if xpixels[i][j+1] == 0:
                break
            else:
                distances[i][j]=math.sqrt(((xpixels[i][j+1]-xpixels[i][j])**2) + ((ypixels[i][j+1]-ypixels[i][j])**2))
            
    return distances

In [38]:

xpixels, ypixels, names, oarrivals, odepartures, latlong = pixelization(124,hinpixel)

39097.31413
71910.02156
77388.55087
85301.80221
91576.1033
nan
dTime
29239.4693
57297.69063
61480.66534
68346.75738
nan
dTime
dTime
28883.25981
57642.36077
nan
dTime
dTime
dTime
dTime
28515.55434
57043.12402
63987.60518
nan
dTime
dTime
dTime
28401.76928
56888.61875
62656.41347
nan
dTime
dTime
dTime
27368.50559
57629.2452
63343.67296
nan
dTime
dTime
dTime
27659.39777
57393.90247
64318.99363
67982.53847
72619.70497
77316.53861
84123.60382
30044.70594
57230.72229
61064.4705
67788.15072
nan
dTime
dTime
29519.73661
58619.05505
63429.53289
nan
dTime
dTime
dTime
25468.85845
59180.69034
67369.40147
nan
dTime
dTime
dTime
28364.90155
56800.00794
61423.5845
66618.09958
72829.74847
nan
dTime
29312.16449
57841.59186
64431.31476
nan
dTime
dTime
dTime
28066.24596
57113.97759
nan
dTime
dTime
dTime
dTime
28248.4346
57654.99393
63017.70917
nan
dTime
dTime
dTime
27662.30785
58375.31037
63776.64329
66231.38059
72189.31205
nan
dTime
28998.95125
57133.8928
nan
dTime
dTime
dTime
dTime
27688.42282
57887.35791

In [39]:
xpixels

array([[ 2403.,  2393.,  2403.,  2426.,  2426.,  2403.,     0.],
       [ 2403.,  2404.,  2403.,  2431.,  2403.,     0.,     0.],
       [ 2403.,  2404.,  2403.,     0.,     0.,     0.,     0.],
       [ 2403.,  2404.,  2413.,  2403.,     0.,     0.,     0.],
       [ 2403.,  2404.,  2422.,  2403.,     0.,     0.,     0.],
       [ 2403.,  2404.,  2404.,  2403.,     0.,     0.,     0.],
       [ 2403.,  2404.,  2413.,  2403.,  2405.,  2403.,  2422.],
       [ 2403.,  2404.,  2403.,  2404.,  2403.,     0.,     0.],
       [ 2403.,  2404.,  2396.,  2403.,     0.,     0.,     0.],
       [ 2403.,  2439.,  2403.,  2403.,     0.,     0.,     0.],
       [ 2403.,  2404.,  2403.,  2403.,  2409.,  2403.,     0.],
       [ 2403.,  2404.,  2398.,  2403.,     0.,     0.,     0.],
       [ 2403.,  2404.,  2403.,     0.,     0.,     0.,     0.],
       [ 2403.,  2404.,  2396.,  2403.,     0.,     0.,     0.],
       [ 2403.,  2404.,  2407.,  2403.,  2400.,  2403.,     0.],
       [ 2403.,  2404.,  

In [40]:
dist = cartDist(124,xpixels, ypixels)
odepartures

array([[ 39097.31413,  71910.02156,  77388.55087,  85301.80221,
             0.     ,      0.     ,      0.     ],
       [ 29239.4693 ,  57297.69063,  61480.66534,  68346.75738,
             0.     ,      0.     ,      0.     ],
       [ 28883.25981,  57642.36077,      0.     ,      0.     ,
             0.     ,      0.     ,      0.     ],
       [ 28515.55434,  57043.12402,  63987.60518,      0.     ,
             0.     ,      0.     ,      0.     ],
       [ 28401.76928,  56888.61875,  62656.41347,      0.     ,
             0.     ,      0.     ,      0.     ],
       [ 27368.50559,  57629.2452 ,  63343.67296,      0.     ,
             0.     ,      0.     ,      0.     ],
       [ 27659.39777,  57393.90247,  64318.99363,  67982.53847,
         72619.70497,  77316.53861,  84123.60382],
       [ 30044.70594,  57230.72229,  61064.4705 ,  67788.15072,
             0.     ,      0.     ,      0.     ],
       [ 29519.73661,  58619.05505,  63429.53289,      0.     ,
             0. 

In [41]:
np.sum(dist, axis=1)

array([  66.78573207,   62.29270211,    2.82842712,   26.90943219,
         38.76747433,    5.23606798,   47.05566675,   52.03998401,
         20.21954446,  111.79543677,   45.81399563,   41.95460054,
          2.82842712,   20.21954446,   26.13663467,    2.        ,
         48.52306576,  111.99038555,   57.37189674,   47.77283723,
        110.97470619,   36.79561307,    7.30056308,   47.69463864,
          5.23606798,   36.84902551,    2.        ,   50.96606988,
         57.36438182,   47.10852163,   46.79601263,    7.16227766,
         31.42980449,   45.56428309,   80.75717865,  140.20960881,
        150.44119145,   46.96305193,   97.67745377,   55.1098878 ,
        117.75055402,  142.39916218,  190.50084893,  172.76289083,
        174.20438111,  185.23867608,  212.41200341,  216.97761006,
        119.65114273,  144.57315569,  151.25263144,  220.77137496,
        226.37581542,  221.90927938,   66.48506934,   73.67277482,
        129.34702494,   34.23448554,   98.16124394,   62.38832

In [42]:
len(np.nonzero(dist)[0])

389

In [43]:
print(dist)

[[  10.19803903   10.19803903   23.19482701    0.           23.19482701
     0.        ]
 [   1.41421356    1.41421356   29.73213749   29.73213749    0.            0.        ]
 [   1.41421356    1.41421356    0.            0.            0.            0.        ]
 [   1.41421356   12.04159458   13.45362405    0.            0.            0.        ]
 [   1.41421356   18.24828759   19.10497317    0.            0.            0.        ]
 [   1.            2.            2.23606798    0.            0.            0.        ]
 [   1.           10.81665383   11.66190379    2.23606798    2.23606798
    19.10497317]
 [   1.            1.           25.01999201   25.01999201    0.            0.        ]
 [   1.           10.            9.21954446    0.            0.            0.        ]
 [  53.07541804   42.72001873   16.            0.            0.            0.        ]
 [   1.            1.            3.           21.84032967   18.97366596
     0.        ]
 [   1.41421356   19.92485885   20.61

In [46]:
def tripInfo(n, distances, odepartures):
    count = 0
    tripsPP= np.zeros(n)
    tripsPH = np.zeros(24)
    for i in range(n):
        for j in range(6):
            if distances[i][j] == 0:
                count = 0
            else:
                tripsPP[i] += 1
            if np.isnan(odepartures[i][j]) or odepartures[i][j] == 0:
                count = 0
            else:
                tripsPH[math.floor(odepartures[i][j]/3600)] += 1;
                
    return tripsPP, tripsPH
    
            

In [48]:
tripInfo(124, dist, odepartures)

(array([ 4.,  4.,  2.,  3.,  3.,  3.,  6.,  4.,  3.,  3.,  5.,  3.,  2.,
         3.,  5.,  2.,  4.,  6.,  5.,  4.,  4.,  3.,  4.,  4.,  3.,  3.,
         2.,  5.,  5.,  3.,  3.,  3.,  3.,  3.,  5.,  4.,  3.,  3.,  3.,
         3.,  4.,  5.,  3.,  3.,  3.,  5.,  3.,  3.,  5.,  4.,  4.,  2.,
         3.,  3.,  4.,  3.,  5.,  2.,  6.,  3.,  5.,  5.,  4.,  5.,  5.,
         4.,  5.,  6.,  4.,  4.,  5.,  6.,  5.,  4.,  3.,  6.,  4.,  4.,
         2.,  3.,  6.,  4.,  4.,  0.,  2.,  0.,  2.,  2.,  2.,  0.,  0.,
         0.,  2.,  3.,  4.,  2.,  4.,  2.,  4.,  2.,  0.,  0.,  2.,  2.,
         2.,  0.,  2.,  2.,  3.,  2.,  2.,  2.,  0.,  2.,  4.,  2.,  2.,
         3.,  2.,  3.,  0.,  0.,  0.,  2.]),
 array([  0.,   0.,   0.,   0.,   0.,   3.,   5.,  33.,  25.,   6.,  25.,
         19.,  19.,  14.,   7.,  22.,  36.,  33.,  38.,  23.,  32.,  28.,
          8.,   8.,   4.]))

In [49]:
pixels = np.zeros((10000,3))
latlong

array([[   41.4122136 ,   -74.3321119 , -3078.25729534],
       [   41.430352  ,   -74.423366  , -3083.3862504 ],
       [   41.4122136 ,   -74.3321119 , -3078.25729534],
       ..., 
       [           nan,            nan,            nan],
       [           nan,            nan,            nan],
       [           nan,            nan,            nan]])

In [50]:
u_pixels = np.unique(latlong, axis = 0)

In [51]:
i = 0
while True:
    pixels[i][0] = u_pixels[i][0]
    pixels[i][1] = u_pixels[i][1]
    pixels[i][2] = np.count_nonzero(latlong == u_pixels[i][2])
    i = i + 1
    if np.isnan(u_pixels[i][0]):
        break
pixels

array([[ 40.663478, -74.698199,   1.      ],
       [ 40.685392, -74.636074,   1.      ],
       [ 40.700506, -73.909676,   1.      ],
       ..., 
       [  0.      ,   0.      ,   0.      ],
       [  0.      ,   0.      ,   0.      ],
       [  0.      ,   0.      ,   0.      ]])

In [56]:
xpixels

array([[ 2403.,  2393.,  2403.,  2426.,  2426.,  2403.,     0.],
       [ 2403.,  2404.,  2403.,  2431.,  2403.,     0.,     0.],
       [ 2403.,  2404.,  2403.,     0.,     0.,     0.,     0.],
       [ 2403.,  2404.,  2413.,  2403.,     0.,     0.,     0.],
       [ 2403.,  2404.,  2422.,  2403.,     0.,     0.,     0.],
       [ 2403.,  2404.,  2404.,  2403.,     0.,     0.,     0.],
       [ 2403.,  2404.,  2413.,  2403.,  2405.,  2403.,  2422.],
       [ 2403.,  2404.,  2403.,  2404.,  2403.,     0.,     0.],
       [ 2403.,  2404.,  2396.,  2403.,     0.,     0.,     0.],
       [ 2403.,  2439.,  2403.,  2403.,     0.,     0.,     0.],
       [ 2403.,  2404.,  2403.,  2403.,  2409.,  2403.,     0.],
       [ 2403.,  2404.,  2398.,  2403.,     0.,     0.,     0.],
       [ 2403.,  2404.,  2403.,     0.,     0.,     0.,     0.],
       [ 2403.,  2404.,  2396.,  2403.,     0.,     0.,     0.],
       [ 2403.,  2404.,  2407.,  2403.,  2400.,  2403.,     0.],
       [ 2403.,  2404.,  

In [57]:
ypixels

array([[ 610.,  612.,  610.,  613.,  613.,  610.,    0.],
       [ 610.,  609.,  610.,  620.,  610.,    0.,    0.],
       [ 610.,  611.,  610.,    0.,    0.,    0.,    0.],
       [ 610.,  609.,  601.,  610.,    0.,    0.,    0.],
       [ 610.,  611.,  608.,  610.,    0.,    0.,    0.],
       [ 610.,  610.,  608.,  610.,    0.,    0.,    0.],
       [ 610.,  610.,  604.,  610.,  609.,  610.,  608.],
       [ 610.,  610.,  610.,  635.,  610.,    0.,    0.],
       [ 610.,  610.,  604.,  610.,    0.,    0.,    0.],
       [ 610.,  571.,  594.,  610.,    0.,    0.,    0.],
       [ 610.,  610.,  610.,  613.,  592.,  610.,    0.],
       [ 610.,  611.,  630.,  610.,    0.,    0.,    0.],
       [ 610.,  609.,  610.,    0.,    0.,    0.,    0.],
       [ 610.,  610.,  604.,  610.,    0.,    0.,    0.],
       [ 610.,  611.,  612.,  610.,  602.,  610.,    0.],
       [ 610.,  610.,  610.,    0.,    0.,    0.,    0.],
       [ 610.,  611.,  610.,  619.,  610.,    0.,    0.],
       [ 610.,

In [55]:
import csv

with open('pixels.csv', 'w') as csvFile:
    writer = csv.writer(csvFile)
    writer.writerows(pixels)

csvFile.close()
