In [1]:
import numpy as np
import pandas as pd
import math

In [2]:
run1OC = pd.read_csv("NewYork_36071_Module6NN1stRun.csv")
run2OC = pd.read_csv("NewYork36071Module1NN2ndRun.csv")

/Users/wylyanderson/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2698: DtypeWarning: Columns (52,53,54,55,61,62,63,64) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


In [3]:
run1OC.head()

Residence State  County Code  Tract Code  Block Code    HH ID  \
0               36           71       13900        2021  4668505   
1               36           71         100        1017  4576906   
2               36           71         100        1018  4576932   
3               36           71         100        1019  4576950   
4               36           71         100        1019  4576952   

   Person ID Number  Activity Pattern Node 1 Type Node 1 Predecessor  \
0       36011956118                 2           H                  N   
1       36011691461                 1           H                  N   
2       36011691571                 1           H                  N   
3       36011691625                 1           H                  N   
4       36011691633                 1           H                  N   

  Node 1 Successor          ...          Node 6 Departure Time  Node 7 Type  \
0                S          ...                          dTime          NaN   
1                S          ...                          dTime          NaN   
2                S          ...                          dTime          NaN   
3                S          ...                          dTime          NaN   
4                S          ...                          dTime          NaN   

   Node 7 Predecessor  Node 7 Successor  Node 7 Name Node 7 County Node 7 Lat  \
0                 NaN               NaN          NaN           NaN        NaN   
1                 NaN               NaN          NaN           NaN        NaN   
2                 NaN               NaN          NaN           NaN        NaN   
3                 NaN               NaN          NaN           NaN        NaN   
4                 NaN               NaN          NaN           NaN        NaN   

  Node 7 Lon Node 7 Arrival Time Node 7 Departure Time  
0        NaN               oTime                 dTime  
1        NaN               oTime                 dTime  
2        NaN               oTime                 dTime  
3        NaN               oTime                 dTime  
4        NaN               oTime                 dTime  

[5 rows x 70 columns]

In [4]:
run2OC.head()

Unnamed: 0  Residence State  County Code  Tract Code  Block Code    HH ID  \
0    11690759               36           71         100        1000  4576658   
1    11690760               36           71         100        1000  4576658   
2    11690761               36           71         100        1000  4576659   
3    11690762               36           71         100        1000  4576659   
4    11690763               36           71         100        1001  4576660   

   HH TYPE   Latitude  Longitude  Person ID Number  Age  Sex  Traveler Type  \
0        1  41.517333 -74.012504       36011690760   66    1              6   
1        1  41.517333 -74.012504       36011690761   17    1              1   
2        0  41.517333 -74.012504       36011690762   53    1              5   
3        0  41.517333 -74.012504       36011690763   59    0              5   
4        1  41.517446 -74.014654       36011690764   76    0              6   

   Income Bracket  Income Amount  
0             6.0   69012.044610  
1             0.0       0.000000  
2             1.0    2409.692110  
3             1.0    6393.542108  
4             5.0   45906.476360

In [5]:
households2 =  len(run2OC['HH ID'].unique())
print('Number of unique households: ' + str(households2))

numPeople2 = len(run2OC['Person ID Number'].unique())
print('Number of unique people: ' + str(numPeople2))

Number of unique households: 126132
Number of unique people: 372813


In [6]:
allyHHID = run1OC[run1OC['HH ID']==4643185]
print(allyHHID)

        Residence State  County Code  Tract Code  Block Code    HH ID  \
56600                36           71       12200        1017  4643185   
56601                36           71       12200        1017  4643185   
56602                36           71       12200        1017  4643185   
56603                36           71       12200        1017  4643185   
314699               36           71       12200        1017  4643185   

        Person ID Number  Activity Pattern Node 1 Type Node 1 Predecessor  \
56600        36011882014                 1           H                  N   
56601        36011882015                 1           H                  N   
56602        36011882016                 1           H                  N   
56603        36011882017                 1           H                  N   
314699       36011882013                 6           H                  N   

       Node 1 Successor          ...          Node 6 Departure Time  \
56600                 S    

In [7]:
allyHHID.shape

(5, 70)

In [8]:
#Pixelization Data
n = 138.348
def Xpixel(latitude,longitude):
    if np.isnan(latitude) or np.isnan(longitude):
        return 0
    else:
        xPixel = math.floor(n*(longitude + 97.5)*math.cos(latitude)) 
        return xPixel
  
def Ypixel(latitude,longitude):
    if np.isnan(latitude) or np.isnan(longitude):
        return 0
    else:
        yPixel = math.floor(n*(latitude - 37.0))
        return yPixel

In [9]:
allyHHID = np.asarray(allyHHID)

In [10]:
allyHHID

array([[36, 71, 12200, 1017, 4643185, 36011882014, 1, 'H', 'N', 'S',
        'Home', 36071, 41.4122136, -74.3321119, 0, '29131.19432', 'S', 'H',
        'O', 'SCOTCHTOWN AVENUE SCHOOL', 36071.0, 41.414171, -74.323418,
        '29187.69993', '58203.18873', 'O', 'S', 'H', nan, 36071.0,
        41.400628999999995, -74.330281, '58323.43963', '64359.37662', 'H',
        'O', 'N', 'Home', 36071.0, 41.4122136, -74.3321119, '63617.33476',
        nan, nan, nan, nan, nan, nan, nan, nan, 'oTime', 'dTime', nan, nan,
        nan, nan, nan, nan, nan, 'oTime', 'dTime', nan, nan, nan, nan, nan,
        nan, nan, 'oTime', 'dTime'],
       [36, 71, 12200, 1017, 4643185, 36011882015, 1, 'H', 'N', 'S',
        'Home', 36071, 41.4122136, -74.3321119, 0, '28638.77485', 'S', 'H',
        'O', 'SCOTCHTOWN AVENUE SCHOOL', 36071.0, 41.414171, -74.323418,
        '28695.28046', '59242.29968', 'O', 'S', 'H',
        'SLEEPY HILLS ORCHARD', 36071.0, 41.365066999999996,
        -74.50639100000001, '60452.42241', '

In [11]:
run1OC_array = np.asarray(run1OC)

In [12]:
run1OC_array

array([[36, 71, 13900, ..., nan, 'oTime', 'dTime'],
       [36, 71, 100, ..., nan, 'oTime', 'dTime'],
       [36, 71, 100, ..., nan, 'oTime', 'dTime'],
       ..., 
       [36, 71, 15200, ..., nan, 'oTime', 'dTime'],
       [36, 71, 15200, ..., nan, 'oTime', 'dTime'],
       [36, 71, 15200, ..., nan, 'oTime', 'dTime']], dtype=object)

In [13]:
allyHHID

array([[36, 71, 12200, 1017, 4643185, 36011882014, 1, 'H', 'N', 'S',
        'Home', 36071, 41.4122136, -74.3321119, 0, '29131.19432', 'S', 'H',
        'O', 'SCOTCHTOWN AVENUE SCHOOL', 36071.0, 41.414171, -74.323418,
        '29187.69993', '58203.18873', 'O', 'S', 'H', nan, 36071.0,
        41.400628999999995, -74.330281, '58323.43963', '64359.37662', 'H',
        'O', 'N', 'Home', 36071.0, 41.4122136, -74.3321119, '63617.33476',
        nan, nan, nan, nan, nan, nan, nan, nan, 'oTime', 'dTime', nan, nan,
        nan, nan, nan, nan, nan, 'oTime', 'dTime', nan, nan, nan, nan, nan,
        nan, nan, 'oTime', 'dTime'],
       [36, 71, 12200, 1017, 4643185, 36011882015, 1, 'H', 'N', 'S',
        'Home', 36071, 41.4122136, -74.3321119, 0, '28638.77485', 'S', 'H',
        'O', 'SCOTCHTOWN AVENUE SCHOOL', 36071.0, 41.414171, -74.323418,
        '28695.28046', '59242.29968', 'O', 'S', 'H',
        'SLEEPY HILLS ORCHARD', 36071.0, 41.365066999999996,
        -74.50639100000001, '60452.42241', '

In [33]:
def pixelization(n,a):
    xpixels =  np.zeros((n,7))
    ypixels =  np.zeros((n,7))
    oarrivals = np.zeros((n,7))
    odepartures = np.zeros((n,7))
    latlong = np.zeros((n*7,3))

    name = [[] for _ in range(n)]
    for i in range(n):
        for j in range(7):
            xpixels[i][j]= Xpixel(a[i][12+9*j],a[i][13+9*j])
            ypixels[i][j]= Ypixel(a[i][12+9*j],a[i][13+9*j])
            latlong[i*7 + j][0] = a[i][12+9*j]
            latlong[i*7 + j][1] = a[i][13+9*j]
            latlong[i*7 + j ][2] = a[i][13+9*j]*a[i][12+9*j]
            if a[i][14+9*j] != 'oTime':
                oarrivals[i][j]= (a[i][14+9*j])
            else:
                oarrivals[i][j]= 0
            if a[i][15+9*j] != 'dTime':
                odepartures[i][j]= (a[i][15+9*j])
            else:
                odepartures[i][j]= 0
            name[i] = np.append(name[i], a[i][10+9*j])
    return xpixels, ypixels, name, oarrivals, odepartures, latlong


In [25]:
pixelization(5, allyHHID)

(array([[-2696., -2694., -2716., -2696.,     0.,     0.,     0.],
        [-2696., -2694., -2754., -2696.,     0.,     0.,     0.],
        [-2696., -2694., -2696.,     0.,     0.,     0.,     0.],
        [-2696., -2694., -2448., -2696., -2716., -2696.,     0.],
        [-2696., -2554., -2554., -2696.,     0.,     0.,     0.]]),
 array([[ 610.,  610.,  608.,  610.,    0.,    0.,    0.],
        [ 610.,  610.,  603.,  610.,    0.,    0.,    0.],
        [ 610.,  610.,  610.,    0.,    0.,    0.,    0.],
        [ 610.,  610.,  629.,  610.,  608.,  610.,    0.],
        [ 610.,  619.,  619.,  610.,    0.,    0.,    0.]]),
 [array(['Home', 'SCOTCHTOWN AVENUE SCHOOL', 'nan', 'Home', 'nan', 'nan',
         'nan'],
        dtype='<U32'),
  array(['Home', 'SCOTCHTOWN AVENUE SCHOOL', 'SLEEPY HILLS ORCHARD', 'Home',
         'nan', 'nan', 'nan'],
        dtype='<U32'),
  array(['Home', 'SCOTCHTOWN AVENUE SCHOOL', 'Home', 'nan', 'nan', 'nan',
         'nan'],
        dtype='<U32'),
  array(['Ho

In [16]:
def cartDist(n, xpixels, ypixels):
    distances = np.zeros((n,7))
    for i in range(n):
        for j in range(7):
            if xpixels[i][j+1] == 0:
                break
            else:
                distances[i][j]=math.sqrt(((xpixels[i][j+1]-xpixels[i][j])**2) + ((ypixels[i][j+1]-ypixels[i][j])**2))
            
    return distances

In [34]:
xpixels, ypixels, names, oarrivals, odepartures, latlong = pixelization(5, allyHHID)

In [18]:
dist = cartDist(5, xpixels, ypixels)

In [19]:
np.sum(dist, axis=1)

array([  44.19047328,  120.82783992,    4.        ,  537.65890903,
        284.56985083])

In [20]:
len(np.nonzero(dist)[0])

15

In [21]:
print(dist)

[[   2.           22.09072203   20.09975124    0.            0.            0.
     0.        ]
 [   2.           60.40695324   58.42088668    0.            0.            0.
     0.        ]
 [   2.            2.            0.            0.            0.            0.
     0.        ]
 [   2.          246.73264883  248.72675771   20.09975124   20.09975124
     0.            0.        ]
 [ 142.28492541    0.          142.28492541    0.            0.            0.
     0.        ]]


In [22]:
def tripInfo(n, distances, odepartures):
    count = 0
    tripsPP= np.zeros(n)
    tripsPH = np.zeros(24)
    for i in range(n):
        for j in range(7):
            if distances[i][j] == 0:
                count = 0
            else:
                tripsPP[i] += 1
            if np.isnan(odepartures[i][j]) or odepartures[i][j] == 0:
                count = 0
            else:
                tripsPH[math.floor(odepartures[i][j]/3600)] += 1;
                
    return tripsPP, tripsPH
    
            

In [23]:
tripInfo(5, dist, odepartures)

(array([ 3.,  3.,  2.,  5.,  2.]),
 array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  3.,  1.,  0.,  1.,  0.,  1.,
         1.,  0.,  1.,  3.,  2.,  1.,  1.,  1.,  0.,  0.,  0.]))

In [36]:
pixels = np.zeros((10000,3))
latlong

array([[   41.4122136 ,   -74.3321119 , -3078.25729534],
       [   41.414171  ,   -74.323418  , -3078.04274236],
       [   41.400629  ,   -74.330281  , -3077.32038715],
       [   41.4122136 ,   -74.3321119 , -3078.25729534],
       [           nan,            nan,            nan],
       [           nan,            nan,            nan],
       [           nan,            nan,            nan],
       [   41.4122136 ,   -74.3321119 , -3078.25729534],
       [   41.414171  ,   -74.323418  , -3078.04274236],
       [   41.365067  ,   -74.506391  , -3081.96185564],
       [   41.4122136 ,   -74.3321119 , -3078.25729534],
       [           nan,            nan,            nan],
       [           nan,            nan,            nan],
       [           nan,            nan,            nan],
       [   41.4122136 ,   -74.3321119 , -3078.25729534],
       [   41.414171  ,   -74.323418  , -3078.04274236],
       [   41.4122136 ,   -74.3321119 , -3078.25729534],
       [           nan,        

In [37]:
u_pixels = np.unique(latlong, axis = 0)

In [45]:
i = 0
while True:
    pixels[i][0] = u_pixels[i][0]
    pixels[i][1] = u_pixels[i][1]
    pixels[i][2] = np.count_nonzero(latlong == u_pixels[i][2])
    i = i + 1
    if np.isnan(u_pixels[i][0]):
        break
pixels

array([[ 41.365067 , -74.506391 ,   1.       ],
       [ 41.400629 , -74.330281 ,   2.       ],
       [ 41.4122136, -74.3321119,  11.       ],
       ..., 
       [  0.       ,   0.       ,   0.       ],
       [  0.       ,   0.       ,   0.       ],
       [  0.       ,   0.       ,   0.       ]])

TypeError: ufunc 'isfinite' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

In [46]:
import csv

with open('pixels.csv', 'w') as csvFile:
    writer = csv.writer(csvFile)
    writer.writerows(pixels)

csvFile.close()
