In [1]:
import numpy as np
import pandas as pd
import math

In [2]:
run1OC = pd.read_csv("NewYork_36071_Module6NN1stRun.csv")
run2OC = pd.read_csv("NewYork36071Module1NN2ndRun.csv")

/Users/wylyanderson/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2698: DtypeWarning: Columns (52,53,54,55,61,62,63,64) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


In [3]:
run1OC.head()

Residence State  County Code  Tract Code  Block Code    HH ID  \
0               36           71       13900        2021  4668505   
1               36           71         100        1017  4576906   
2               36           71         100        1018  4576932   
3               36           71         100        1019  4576950   
4               36           71         100        1019  4576952   

   Person ID Number  Activity Pattern Node 1 Type Node 1 Predecessor  \
0       36011956118                 2           H                  N   
1       36011691461                 1           H                  N   
2       36011691571                 1           H                  N   
3       36011691625                 1           H                  N   
4       36011691633                 1           H                  N   

  Node 1 Successor          ...          Node 6 Departure Time  Node 7 Type  \
0                S          ...                          dTime          NaN   
1                S          ...                          dTime          NaN   
2                S          ...                          dTime          NaN   
3                S          ...                          dTime          NaN   
4                S          ...                          dTime          NaN   

   Node 7 Predecessor  Node 7 Successor  Node 7 Name Node 7 County Node 7 Lat  \
0                 NaN               NaN          NaN           NaN        NaN   
1                 NaN               NaN          NaN           NaN        NaN   
2                 NaN               NaN          NaN           NaN        NaN   
3                 NaN               NaN          NaN           NaN        NaN   
4                 NaN               NaN          NaN           NaN        NaN   

  Node 7 Lon Node 7 Arrival Time Node 7 Departure Time  
0        NaN               oTime                 dTime  
1        NaN               oTime                 dTime  
2        NaN               oTime                 dTime  
3        NaN               oTime                 dTime  
4        NaN               oTime                 dTime  

[5 rows x 70 columns]

In [4]:
run2OC.head()

Unnamed: 0  Residence State  County Code  Tract Code  Block Code    HH ID  \
0    11690759               36           71         100        1000  4576658   
1    11690760               36           71         100        1000  4576658   
2    11690761               36           71         100        1000  4576659   
3    11690762               36           71         100        1000  4576659   
4    11690763               36           71         100        1001  4576660   

   HH TYPE   Latitude  Longitude  Person ID Number  Age  Sex  Traveler Type  \
0        1  41.517333 -74.012504       36011690760   66    1              6   
1        1  41.517333 -74.012504       36011690761   17    1              1   
2        0  41.517333 -74.012504       36011690762   53    1              5   
3        0  41.517333 -74.012504       36011690763   59    0              5   
4        1  41.517446 -74.014654       36011690764   76    0              6   

   Income Bracket  Income Amount  
0             6.0   69012.044610  
1             0.0       0.000000  
2             1.0    2409.692110  
3             1.0    6393.542108  
4             5.0   45906.476360

In [5]:
households2 =  len(run2OC['HH ID'].unique())
print('Number of unique households: ' + str(households2))

numPeople2 = len(run2OC['Person ID Number'].unique())
print('Number of unique people: ' + str(numPeople2))

Number of unique households: 126132
Number of unique people: 372813


In [6]:
allyHHID = run1OC[run1OC['HH ID']==4643185]
print(allyHHID)

        Residence State  County Code  Tract Code  Block Code    HH ID  \
56600                36           71       12200        1017  4643185   
56601                36           71       12200        1017  4643185   
56602                36           71       12200        1017  4643185   
56603                36           71       12200        1017  4643185   
314699               36           71       12200        1017  4643185   

        Person ID Number  Activity Pattern Node 1 Type Node 1 Predecessor  \
56600        36011882014                 1           H                  N   
56601        36011882015                 1           H                  N   
56602        36011882016                 1           H                  N   
56603        36011882017                 1           H                  N   
314699       36011882013                 6           H                  N   

       Node 1 Successor          ...          Node 6 Departure Time  \
56600                 S    

In [7]:
allyHHID.shape

(5, 70)

In [8]:
#Pixelization Data
n = 138.348
def Xpixel(latitude,longitude):
    if np.isnan(latitude) or np.isnan(longitude):
        return 0
    else:
        xPixel = math.floor(n*(longitude + 97.5)*math.cos(math.radians(latitude))) 
    return xPixel
  
def Ypixel(latitude,longitude):
    if np.isnan(latitude) or np.isnan(longitude):
        return 0
    else:
        yPixel = math.floor(n*(latitude - 37.0))
        return yPixel

In [9]:
def baselat(ypixel):
    lat = ypixel/n + 37
    return lat

In [10]:
def endlat(ypixel):
    lat = (ypixel+1)/n + 37
    return lat

In [31]:
def baselong(xpixel, ypixel):
    lat = endlat(ypixel)
    return (xpixel/math.cos(math.radians(lat))/n) -97.5
def endlong(xpixel, ypixel):
    lat = baselat(ypixel)
    return ((xpixel+1)/math.cos(math.radians(lat))/n) -97.5    

In [32]:
baselat(610)

41.40917107583774

In [33]:
endlat(610)

41.41639922514239

In [34]:
baselong(2403,610)


-74.33859336548741

In [35]:
endlong(2403,610)

-74.33153294110518

In [36]:
hinpixel = run2OC[run2OC['Latitude']>=baselat(610)]
hinpixel = hinpixel[hinpixel['Latitude']<endlat(610)]
hinpixel = hinpixel[hinpixel['Longitude']>=baselong(2403, 610)]
hinpixel = hinpixel[hinpixel['Longitude']<endlong(2403, 610)]
 

In [37]:
hinpixel

Unnamed: 0  Residence State  County Code  Tract Code  Block Code  \
180384    11871143               36           71       11900        1017   
180385    11871144               36           71       11900        1017   
180386    11871145               36           71       11900        1017   
180387    11871146               36           71       11900        1017   
180388    11871147               36           71       11900        1017   
180389    11871148               36           71       11900        1017   
180390    11871149               36           71       11900        1017   
180391    11871150               36           71       11900        1017   
180392    11871151               36           71       11900        1017   
180393    11871152               36           71       11900        1017   
180394    11871153               36           71       11900        1017   
180395    11871154               36           71       11900        1017   
180396    11871155               36           71       11900        1017   
180397    11871156               36           71       11900        1017   
180398    11871157               36           71       11900        1017   
180399    11871158               36           71       11900        1017   
180400    11871159               36           71       11900        1017   
180401    11871160               36           71       11900        1017   
180402    11871161               36           71       11900        1017   
180403    11871162               36           71       11900        1017   
180404    11871163               36           71       11900        1017   
180405    11871164               36           71       11900        1017   
180406    11871165               36           71       11900        1017   
180407    11871166               36           71       11900        1017   
180408    11871167               36           71       11900        1017   
180409    11871168               36           71       11900        1017   
180410    11871169               36           71       11900        1017   
180411    11871170               36           71       11900        1017   
181759    11872518               36           71       11900        1063   
181760    11872519               36           71       11900        1063   
...            ...              ...          ...         ...         ...   
191255    11882014               36           71       12200        1017   
191256    11882015               36           71       12200        1017   
191257    11882016               36           71       12200        1017   
191258    11882017               36           71       12200        1017   
191259    11882018               36           71       12200        1017   
191260    11882019               36           71       12200        1017   
191261    11882020               36           71       12200        1017   
191262    11882021               36           71       12200        1017   
191263    11882022               36           71       12200        1017   
191264    11882023               36           71       12200        1017   
191265    11882024               36           71       12200        1017   
191266    11882025               36           71       12200        1017   
191267    11882026               36           71       12200        1017   
191268    11882027               36           71       12200        1017   
191269    11882028               36           71       12200        1017   
191270    11882029               36           71       12200        1017   
191271    11882030               36           71       12200        1017   
191272    11882031               36           71       12200        1017   
191273    11882032               36           71       12200        1017   
191274    11882033               36           71       12200        1017   
191275    11882034               36           71       1

In [18]:
allyHHID = np.asarray(allyHHID)

In [19]:
allyHHID

array([[36, 71, 12200, 1017, 4643185, 36011882014, 1, 'H', 'N', 'S',
        'Home', 36071, 41.4122136, -74.3321119, 0, '29131.19432', 'S', 'H',
        'O', 'SCOTCHTOWN AVENUE SCHOOL', 36071.0, 41.414171, -74.323418,
        '29187.69993', '58203.18873', 'O', 'S', 'H', nan, 36071.0,
        41.400628999999995, -74.330281, '58323.43963', '64359.37662', 'H',
        'O', 'N', 'Home', 36071.0, 41.4122136, -74.3321119, '63617.33476',
        nan, nan, nan, nan, nan, nan, nan, nan, 'oTime', 'dTime', nan, nan,
        nan, nan, nan, nan, nan, 'oTime', 'dTime', nan, nan, nan, nan, nan,
        nan, nan, 'oTime', 'dTime'],
       [36, 71, 12200, 1017, 4643185, 36011882015, 1, 'H', 'N', 'S',
        'Home', 36071, 41.4122136, -74.3321119, 0, '28638.77485', 'S', 'H',
        'O', 'SCOTCHTOWN AVENUE SCHOOL', 36071.0, 41.414171, -74.323418,
        '28695.28046', '59242.29968', 'O', 'S', 'H',
        'SLEEPY HILLS ORCHARD', 36071.0, 41.365066999999996,
        -74.50639100000001, '60452.42241', '

In [20]:
run1OC_array = np.asarray(run1OC)

In [21]:
run1OC_array

array([[36, 71, 13900, ..., nan, 'oTime', 'dTime'],
       [36, 71, 100, ..., nan, 'oTime', 'dTime'],
       [36, 71, 100, ..., nan, 'oTime', 'dTime'],
       ..., 
       [36, 71, 15200, ..., nan, 'oTime', 'dTime'],
       [36, 71, 15200, ..., nan, 'oTime', 'dTime'],
       [36, 71, 15200, ..., nan, 'oTime', 'dTime']], dtype=object)

In [22]:
allyHHID

array([[36, 71, 12200, 1017, 4643185, 36011882014, 1, 'H', 'N', 'S',
        'Home', 36071, 41.4122136, -74.3321119, 0, '29131.19432', 'S', 'H',
        'O', 'SCOTCHTOWN AVENUE SCHOOL', 36071.0, 41.414171, -74.323418,
        '29187.69993', '58203.18873', 'O', 'S', 'H', nan, 36071.0,
        41.400628999999995, -74.330281, '58323.43963', '64359.37662', 'H',
        'O', 'N', 'Home', 36071.0, 41.4122136, -74.3321119, '63617.33476',
        nan, nan, nan, nan, nan, nan, nan, nan, 'oTime', 'dTime', nan, nan,
        nan, nan, nan, nan, nan, 'oTime', 'dTime', nan, nan, nan, nan, nan,
        nan, nan, 'oTime', 'dTime'],
       [36, 71, 12200, 1017, 4643185, 36011882015, 1, 'H', 'N', 'S',
        'Home', 36071, 41.4122136, -74.3321119, 0, '28638.77485', 'S', 'H',
        'O', 'SCOTCHTOWN AVENUE SCHOOL', 36071.0, 41.414171, -74.323418,
        '28695.28046', '59242.29968', 'O', 'S', 'H',
        'SLEEPY HILLS ORCHARD', 36071.0, 41.365066999999996,
        -74.50639100000001, '60452.42241', '

In [23]:
def pixelization(n,a):
    xpixels =  np.zeros((n,7))
    ypixels =  np.zeros((n,7))
    oarrivals = np.zeros((n,7))
    odepartures = np.zeros((n,7))
    latlong = np.zeros((n*7,3))

    name = [[] for _ in range(n)]
    for i in range(n):
        for j in range(7):
            xpixels[i][j]= Xpixel(a[i][12+9*j],a[i][13+9*j])
            ypixels[i][j]= Ypixel(a[i][12+9*j],a[i][13+9*j])
            latlong[i*7 + j][0] = a[i][12+9*j]
            latlong[i*7 + j][1] = a[i][13+9*j]
            latlong[i*7 + j ][2] = a[i][13+9*j]*a[i][12+9*j]
            if a[i][14+9*j] != 'oTime':
                oarrivals[i][j]= (a[i][14+9*j])
            else:
                oarrivals[i][j]= 0
            if a[i][15+9*j] != 'dTime':
                odepartures[i][j]= (a[i][15+9*j])
            else:
                odepartures[i][j]= 0
            name[i] = np.append(name[i], a[i][10+9*j])
    return xpixels, ypixels, name, oarrivals, odepartures, latlong


In [24]:
pixelization(5, allyHHID)

(array([[ 2403.,  2404.,  2404.,  2403.,     0.,     0.,     0.],
        [ 2403.,  2404.,  2387.,  2403.,     0.,     0.,     0.],
        [ 2403.,  2404.,  2403.,     0.,     0.,     0.,     0.],
        [ 2403.,  2404.,  2416.,  2403.,  2404.,  2403.,     0.],
        [ 2403.,  2382.,  2382.,  2403.,     0.,     0.,     0.]]),
 array([[ 610.,  610.,  608.,  610.,    0.,    0.,    0.],
        [ 610.,  610.,  603.,  610.,    0.,    0.,    0.],
        [ 610.,  610.,  610.,    0.,    0.,    0.,    0.],
        [ 610.,  610.,  629.,  610.,  608.,  610.,    0.],
        [ 610.,  619.,  619.,  610.,    0.,    0.,    0.]]),
 [array(['Home', 'SCOTCHTOWN AVENUE SCHOOL', 'nan', 'Home', 'nan', 'nan',
         'nan'],
        dtype='<U32'),
  array(['Home', 'SCOTCHTOWN AVENUE SCHOOL', 'SLEEPY HILLS ORCHARD', 'Home',
         'nan', 'nan', 'nan'],
        dtype='<U32'),
  array(['Home', 'SCOTCHTOWN AVENUE SCHOOL', 'Home', 'nan', 'nan', 'nan',
         'nan'],
        dtype='<U32'),
  array(['Ho

In [ ]:
def cartDist(n, xpixels, ypixels):
    distances = np.zeros((n,7))
    for i in range(n):
        for j in range(7):
            if xpixels[i][j+1] == 0:
                break
            else:
                distances[i][j]=math.sqrt(((xpixels[i][j+1]-xpixels[i][j])**2) + ((ypixels[i][j+1]-ypixels[i][j])**2))
            
    return distances

In [ ]:
xpixels, ypixels, names, oarrivals, odepartures, latlong = pixelization(5, allyHHID)

In [ ]:
dist = cartDist(5, xpixels, ypixels)

In [ ]:
np.sum(dist, axis=1)

In [ ]:
len(np.nonzero(dist)[0])

In [ ]:
print(dist)

In [ ]:
def tripInfo(n, distances, odepartures):
    count = 0
    tripsPP= np.zeros(n)
    tripsPH = np.zeros(24)
    for i in range(n):
        for j in range(7):
            if distances[i][j] == 0:
                count = 0
            else:
                tripsPP[i] += 1
            if np.isnan(odepartures[i][j]) or odepartures[i][j] == 0:
                count = 0
            else:
                tripsPH[math.floor(odepartures[i][j]/3600)] += 1;
                
    return tripsPP, tripsPH
    
            

In [ ]:
tripInfo(5, dist, odepartures)

In [ ]:
pixels = np.zeros((10000,3))
latlong

In [ ]:
u_pixels = np.unique(latlong, axis = 0)

In [ ]:
i = 0
while True:
    pixels[i][0] = u_pixels[i][0]
    pixels[i][1] = u_pixels[i][1]
    pixels[i][2] = np.count_nonzero(latlong == u_pixels[i][2])
    i = i + 1
    if np.isnan(u_pixels[i][0]):
        break
pixels

In [ ]:
def 

In [ ]:
import csv

with open('pixels.csv', 'w') as csvFile:
    writer = csv.writer(csvFile)
    writer.writerows(pixels)

csvFile.close()
